version: '3'
services:
    redis-server:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 7379:7379

    redis-exporter:
        image: oliver006/redis_exporter
        ports:
            - 9121:9121
        links:
            - redis-server:redis-server
        environment:
            - REDIS_ADDR=redis://redis-server:7379
        depends_on:
            - redis-server


    prometheus-server:
        image: prom/prometheus
        ports:
            - 9090:9090
        volumes:
            - ./prometheus.yml:/etc/prometheus/prometheus.yml
        depends_on:
            - redis-exporter
            - redis-server

    grafana-ui:
        image: grafana/grafana
        ports:
            - 3000:3000
        environment:
            - GF_SECURITY_ADMIN_PASSWORD=secret
        links:
            - prometheus-server:prometheus
        depends_on:
            - redis-server
            - redis-exporter
            - prometheus-server
            
            

    
    